import type { Product } from '@/lib/types';

export const PRODUCTS: Product[] = [
  {
    id: 'trench-coat-editorial',
    name: 'Trench Coat Editorial',
    priceCents: 129900,
    imageUrl: '/images/trench-coat-editorial.jpg',
    category: 'feminino',
    featured: true,
  },
  {
    id: 'vestido-slip-cetim',
    name: 'Vestido Slip Cetim',
    priceCents: 69900,
    imageUrl: '/images/vestido-slip-cetim.jpg',
    category: 'feminino',
  },
  {
    id: 'saia-midi-plissada',
    name: 'Saia Midi Plissada',
    priceCents: 39900,
    imageUrl: '/images/saia-midi-plissada.jpg',
    category: 'feminino',
  },
  {
    id: 'blazer-oversized',
    name: 'Blazer Oversized',
    priceCents: 89900,
    imageUrl: '/images/blazer-oversized.jpg',
    category: 'masculino',
    featured: true,
  },
  {
    id: 'camisa-seda-manga-longa',
    name: 'Camisa Seda Manga Longa',
    priceCents: 49900,
    imageUrl: '/images/camisa-seda-manga-longa.jpg',
    category: 'masculino',
  },
  {
    id: 'calca-alfaiataria-reta',
    name: 'Calça Alfaiataria Reta',
    priceCents: 59900,
    imageUrl: '/images/calca-alfaiataria-reta.jpg',
    category: 'masculino',
  },
  {
    id: 'cinto-couro-estruturado',
    name: 'Cinto Couro Estruturado',
    priceCents: 19900,
    imageUrl: '/images/cinto-couro-estruturado.jpg',
    category: 'acessorios',
  },
  {
    id: 'oculos-escuros-metal',
    name: 'Óculos Escuros Metal',
    priceCents: 34900,
    imageUrl: '/images/oculos-escuros-metal.jpg',
    category: 'acessorios',
  },
  {
    id: 'colar-corrente-fina',
    name: 'Colar Corrente Fina',
    priceCents: 24900,
    imageUrl: '/images/colar-corrente-fina.jpg',
    category: 'acessorios',
    featured: true,
  },
];
